### ISSUE TITLE
(MR/VR) Clicking block category icon doesn't do quick scroll downwards or is incosistent

### ISSUE THREAD

**Issue by DaviveCZ** [fortellgames/bw_bugtracker#251]
On PC/Mobile when you click the block category icon, It would quick scroll the category you're on downwards.
It was usefull on other platforms if you wanted to get to certain item/block quickly without having to scroll like mad.
in VR you however can't scroll REALLY quick cos holding down the thumbstick would only go as fast as it's set right now. 
I wish this was fixed in MR/VR mainly so the player could scroll through blocks quicker.
Btw when the scrolling gets to bottom and you press the category icon, it would've looped back up.

**Comment by dianateper** [comment]
Fixed in the latest update 2.0.0.105 (96)

**Comment by DaviveCZ** [comment]
https://github.com/user-attachments/assets/f669dd09-780a-4143-b019-a77b73010e41

got this issue now with it. Sometimes it gets stuck in empty page without a way to get out of it unless i reload the world.
on colors it doesn't quick scroll

**Comment by DaviveCZ** [comment]
this in my opinion shouldn't be low priority cos it's easy to get the menu stuck if you click it mulitple times.
i had clicked the action block menu multiple times and ended with empty page. reloading the world doesn't fix this so you need to restart the whole game just to get the menu back...

**Comment by Aktion** [comment]
Its low because an issue is related to global scale, ie its works
perfectly at one number

when we implement locomotion and different scale we will back to this issue

**Comment by DaviveCZ** [comment]
ah alright. thanks for clarifying

**Comment by DaviveCZ** [comment]
https://github.com/user-attachments/assets/e2b74700-9f80-4916-a33e-e183a7efb59b

Latest update semi-fixed it but it occasionaly gets stuck. namely on the Blockster section

**Comment by DaviveCZ** [comment]
This no longer happens in recent updates
